### ISSUE TITLE
[Bug/Crashes] The set command can set the value of a boolean config field to a string

### ISSUE THREAD

**Issue by PieKing1215** [DenisD3D/Commands4Configs#1]
Brought to my attention by [SuntannedDuck2](https://www.curseforge.com/members/suntannedduck2).
From: https://www.curseforge.com/minecraft/mc-mods/invmove?comment=8
His crash log: https://hatebin.com/vifedfauvj

**Description**
When you use /config set, the value is always treated as a String.
This can result in invalid configs if the field being edited is supposed to be a boolean.

**Example**
Generate new singleplayer world
Run "/config forge SERVER set server.fixAdvancementLoading false"
Exit world
Try to load same world and get a crash (same as crashlog at the top):

```
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
	at net.minecraft.advancements.PlayerAdvancements.load(PlayerAdvancements.java:157)
	at net.minecraft.advancements.PlayerAdvancements.<init>(PlayerAdvancements.java:65)
```
The line PlayerAdvancements.java:157 contains:
```
if (net.minecraftforge.common.ForgeConfig.SERVER.fixAdvancementLoading.get()) ...
```

If you go into the world file into serverconfig and look at forge-server.toml, you can see the problem:
The line that should read:
```
fixAdvancementLoading = false
```
is actually set to:
```
fixAdvancementLoading = "false"
```
If the code reading the field doesn't explicitly check the type of the value, the get function throws a ClassCastException and the game crashes.

**Comment by DenisD3D** [comment]
Hi, Sorry for the late reply, I haven't seen your issue earlier :-( 
Indeed I missed some few important type in the config....
A new version is waiting for approval on curseforge
Thanks a lot for reporting
